# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
env:
  global:
  - PKGNAME=ForestGapR

matrix:
  include:
  - r: release
    os: linux
    arch: amd64          # optional, this is default, routes to a full VM
    dist: focal          # or bionic | xenial | trusty | precise with xenial as default
    env: BADGE=linux
    cache:
      - ccache
      - packages
  - r: release
    os: osx
    env:
      - BADGE=osx
    cache:
      - ccache
      - packages
      
  - os: windows
    env:
      - BADGE=windows
    language: bash
    
language: r

deploy:
  provider: releases
  file_glob: true
  file: ${PKGNAME}_${PKGVERSION}_${TRAVIS_OS_NAME}*
  overwrite: true
  cleanup: true
  on:
    repo: carlos-alberto-silva/ForestGapR
    tags: true
