# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
env:
  global:
  - PKGNAME=ForestGapR
    NOT_CRAN: true
    _R_CHECK_FORCE_SUGGESTS: true
    _R_CHECK_CRAN_INCOMING_: true
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
matrix:
  include:
  - r: release
    os: linux
    arch: amd64          # optional, this is default, routes to a full VM
    dist: focal          # or bionic | xenial | trusty | precise with xenial as default
    env: BADGE=linux
    cache:
      - ccache
      - packages
  - r: release
    os: osx
    env:
      - BADGE=osx
    cache:
      - ccache
      - packages
      
  - os: windows
    env:
      - BADGE=windows
    language: bash
    
language: r

script:
  - R CMD build .
  - travis_wait 30 R CMD check *tar.gz --as-cran
  - R CMD INSTALL . --build

  # safelist
branches:
  only:
  - master
  - /^v[\d\.]*$/
before_deploy:
  - 'export PKGVERSION=$(sed -n ''/^Version:/s/Version: \(.*\)/\1/p'' DESCRIPTION)'
  - echo "Upload file glob is $(echo $PKGNAME)_${PKGVERSION}*"

deploy:
  provider: releases
  file_glob: true
  file: ${PKGNAME}_${PKGVERSION}_${TRAVIS_OS_NAME}*
  overwrite: true
  cleanup: true
  on:
    repo: carlos-alberto-silva/ForestGapR
    tags: true
